Crear endpoint de creacion de Rent e index
wolox-training/pm-rails pull request #11
Opened 2019-02-08 14:15 UTC by paul-ot

Added new serializers for users and rents models.
New controller to allow us to create a rent or list rents of a specific user.
Added routes for the above controller.

2019-02-08 19:34 UTC, holywyvern requested changes

2019-02-08 19:34 UTC, holywyvern commented on app/controllers/api/v1/rents_controller.rb
> +        @user = User.find(params[:user_id])
Si estas usando devise_token_auth, seguramente estas pensando en crear la renta usando `current_user` y no user_id como parametro.

Viene de la idea de "yo me creo una renta para mi"

2019-02-08 19:34 UTC, holywyvern commented on app/serializers/user_serializer.rb
> +  0
En este caso, se puede conseguir como object.rents.count

2019-02-12 14:11 UTC, paul-ot reviewed
Implementado cambio  solicitado en UserSerializar.rents_counter

2019-02-12 14:11 UTC, paul-ot commented on app/controllers/api/v1/rents_controller.rb
> +        @user = User.find(params[:user_id])
@holywyvern, vos sabés que lo había implementado como vos decís, usando `current_user`, pero después presté atención a las urls de Apiary, y son de la forma `api/v1/users/1/rents`, lo que me llevó a pensar que se requería que se le pasara el ID del user de esa manera, en vez de utilizar el de Devise.
De cambiarlo, tendría que cambiar el route también, para que sea algo así como `api/v1/rents`.

2019-02-12 14:13 UTC, paul-ot commented on app/serializers/user_serializer.rb
> +  0
Fixed.

2019-02-12 14:45 UTC, holywyvern approved these changes

2019-02-12 15:47 UTC, merged