27 - Crear ruta para creación de un BookSuggestion
wolox-training/pm-rails pull request #14
Opened 2019-02-14 19:09 UTC by paul-ot

- I've set  user as optional in the book suggestions model.
- A new controller has been  created, to allow users to create book suggestions without be logged in.
- Routes for the above controller.

2019-02-14 21:29 UTC, holywyvern requested changes

2019-02-14 21:29 UTC, holywyvern commented on app/controllers/api/v1/book_suggestions_controller.rb
> +        params.permit(:synopsis, :price, :author, :title, :link, :publisher, :year)
Deberías agregar el usuario, si existe:

```rb
params.permit(...).merge(user: current_user)
```

2019-02-14 21:29 UTC, holywyvern commented on app/controllers/api/v1/book_suggestions_controller.rb
> +      def create
Se pueden hacer suggestions de forma anonima, por lo que deberías saltar la autenticación de usuario para create.

2019-02-15 18:51 UTC, paul-ot commented on app/controllers/api/v1/book_suggestions_controller.rb
> +      def create
La auth se aplica en cada controlador individualmente, `before_action :authenticate_user!`, en este no lo apliqué.

2019-02-15 19:22 UTC, paul-ot commented on app/controllers/api/v1/book_suggestions_controller.rb
> +        params.permit(:synopsis, :price, :author, :title, :link, :publisher, :year)
Fixed.

2019-02-15 19:36 UTC, paul-ot commented
Cambios listos @mtejedorwolox @holywyvern

2019-02-15 19:47 UTC, holywyvern approved these changes

2019-02-15 19:48 UTC, merged