36 - Integración API Externa
wolox-training/pm-rails pull request #17
Opened 2019-02-18 14:42 UTC by paul-ot

- Añadido endpoint para hacer GET de libros por su ISBN.
- Añadido nuevo controlador para get de libros desde Open Library.
- Añadida clase en app/services, para comunicarnos con Open Library.
- Añadida gema HTTParty, para facilitar el uso de http requests.

2019-02-18 18:24 UTC, holywyvern requested changes

2019-02-18 18:24 UTC, holywyvern commented on app/services/open_library.rb
> +    response = self.class.get('/books', @options)
Que pasa cuando consulto por un ISBN que no existe ?

Deberías agregar un error del estilo:

`raise OpenLibraryError unless response.ok?`

y usar `rescue_from`

2019-02-18 18:28 UTC, paul-ot commented on app/services/open_library.rb
> +    response = self.class.get('/books', @options)
Ah, bien, cuando no existía, la clase devolvía un objeto vacío `{}`, y controlaba  eso en el Controlador, ahora lo arreglo.

2019-02-18 18:57 UTC, paul-ot commented on app/services/open_library.rb
> +    response = self.class.get('/books', @options)
El problema es que por más que no exista el ISBN, la API retorna siempre ok (http:200), que te parece si hago algo como `raise OpenLibraryError if response.body == '{}'`?

2019-02-18 19:11 UTC, holywyvern commented on app/services/open_library.rb
> +    response = self.class.get('/books', @options)
Creo que es mejor que hagas algo como:

```
json = JSON.parse(response.body)
raise OpenLibraryError if json.blank?
json
```

vos @mtejedorwolox, como preferis manejarlo ?

Igual lo que planteaste esta "bien" pero me hace un poco de ruido comparar strings.

2019-02-18 20:33 UTC, paul-ot commented on app/services/open_library.rb
> +    response = self.class.get('/books', @options)
Implementé como vos lo decís @holywyvern.

2019-02-19 14:17 UTC, holywyvern submitted a review, later dismissed

2019-02-19 14:33 UTC, holywyvern approved these changes

2019-02-19 14:57 UTC, merged