24 implementar autenticación
wolox-training/pm-rails pull request #4
Opened 2019-02-04 17:48 UTC by paul-ot

Trello Card: https://trello.com/c/4LadRDIn/24-implementar-autenticaci%C3%B3n

- It has been added the devise_token_auth gem to the project.
- New migration to add missing fields for Lockable, Trackable and Confirmable (User model).
- New migration to manually add fields for devise-token-auth.
- Installation configuration manually added on User model, AppController and Routes.

2019-02-04 19:33 UTC, mtejedorwolox requested changes

2019-02-04 19:33 UTC, mtejedorwolox commented on db/migrate/20190204140743_add_devise_token_auth_fields_to_users.rb
> +    User.reset_column_information
No me gusta llamar a active models desde una migracion, podria haber cosas que desde el contexto de una migracion hagan que todo falle (ejemplo: acts_as_paranoid), para el caso de este tipo de migraciones preferiria que esto se ejecute en otro contexto (un seed?)

2019-02-04 19:33 UTC, mtejedorwolox commented on db/migrate/20190204145406_add_confirmable_and_lockable_fields_to_users.rb
> +  def up
Si no va a haber definicion en `def down` usa `def change`

2019-02-04 19:34 UTC, mtejedorwolox commented on db/migrate/20190204140743_add_devise_token_auth_fields_to_users.rb
> +    User.reset_column_information
Que opinas @holywyvern

2019-02-04 20:14 UTC, holywyvern commented on db/migrate/20190204140743_add_devise_token_auth_fields_to_users.rb
> +    User.reset_column_information
Prefiero los seeds a insertar valores directamente en la BD en una migración, porque es la forma "estandar" de Rails, sin embargo, la misma documentación de Rails muestra esto. "No me parece tan mal" pero me gusta más un seed, definitivamente.

2019-02-04 20:15 UTC, holywyvern commented on db/migrate/20190204145406_add_confirmable_and_lockable_fields_to_users.rb
> +  def up
Si por algun motivo, tu migración es irreversible, podes tirar un raise "ActiveRecord::IrreversibleMigration" pero no parece ser el caso

2019-02-04 20:23 UTC, paul-ot commented on db/migrate/20190204140743_add_devise_token_auth_fields_to_users.rb
> +    User.reset_column_information
Ok, averiguo como invocar a un seed desde migraciones y lo cambio, gracias!

2019-02-04 20:28 UTC, paul-ot commented on db/migrate/20190204140743_add_devise_token_auth_fields_to_users.rb
> +    User.reset_column_information
Ahora que lo pienso un poquito más, la idea sería ligar el seed file con la migración?, o cómo se correría?

2019-02-05 17:28 UTC, mtejedorwolox commented on db/migrate/20190204140743_add_devise_token_auth_fields_to_users.rb
> +    User.reset_column_information
Armate una rake task para hacer lo de asignar el uid-provider desde el mail, move lo de agregar/remover el indice en uid-provider a otra migracion asi podes correr la primera, despues correr la rake task o seed y despues corres la otra migracion

2019-02-05 17:28 UTC, mtejedorwolox commented on db/migrate/20190204140743_add_devise_token_auth_fields_to_users.rb
> +    User.reset_column_information
Asi te aseguras si algun dia alguien corre las migraciones que le falle ahi y asi tenga que cargar si o si los uid-provider

2019-02-05 21:18 UTC, paul-ot commented
Implementados los cambios sugeridos.

2019-02-05 21:29 UTC, holywyvern requested changes

2019-02-05 21:29 UTC, holywyvern commented on db/migrate/20190205205901_add_index_uid_and_provider_to_users.rb
> +  def up
Las migraciones de rails 5 en adelante tienen el change que te permite escribir solo el metodo `change` en lugar de up/down.

Si no me equivoco, add_index es una operación reversible, por lo que puede ir dentro de change.

2019-02-05 21:29 UTC, holywyvern commented on db/migrate/20190204140743_add_devise_token_auth_fields_to_users.rb
> -    end
Lo mismo que en el otro caso, no se si necesitas el remove columns, dado a que add_column en el metodo change es reversible tambien.

2019-02-05 22:12 UTC, paul-ot commented on db/migrate/20190205205901_add_index_uid_and_provider_to_users.rb
> +  def up
Fixed.

2019-02-05 22:14 UTC, paul-ot commented on db/migrate/20190204140743_add_devise_token_auth_fields_to_users.rb
> -    end
Fixed.

2019-02-05 22:15 UTC, paul-ot commented
Aplicados los cambios sugeridos en las migraciones.

2019-02-06 14:29 UTC, holywyvern requested changes

2019-02-06 14:29 UTC, holywyvern commented on config/routes.rb
> +  # devise_for :users
Borra el código comentado

2019-02-06 14:29 UTC, holywyvern commented on config/initializers/devise_token_auth.rb
> +  # Sometimes it's necessary to make several requests to the API at the same
Borrá el código comentado, aunque haya sido autogenerado

2019-02-06 18:06 UTC, paul-ot commented on config/routes.rb
> +  # devise_for :users
Eliminado!

2019-02-06 18:06 UTC, paul-ot commented on config/initializers/devise_token_auth.rb
> +  # Sometimes it's necessary to make several requests to the API at the same
Eliminado!

2019-02-06 18:06 UTC, paul-ot commented
Comentarios eliminados!
Podrían revisar nuevamente?
@holywyvern 
Gracias!

2019-02-06 18:19 UTC, mtejedorwolox approved these changes

2019-02-06 18:28 UTC, merged